#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)


## Start IBus
#export GTK_IM_MODULE=xim
#export QT_IM_MODULE=xim
#export XMODIFIERS=@im=ibus

# invoke global X session script
. /etc/X11/Xsession
